export const NPC_STATE_THRESHOLDS = {
  HUNGER_COMBAT_PENALTY_THRESHOLD: 70,
  HUNGER_COMBAT_SKILL_PENALTY: -10,

  FEAR_REFUSE_ADVANCE_THRESHOLD: 60,
  FEAR_REFUSE_ADVANCE_CHANCE: 30, // 30% chance to refuse

  STRESS_MORALE_DECAY_THRESHOLD: 80,
  STRESS_MORALE_DECAY_PENALTY: -5, // extra morale decay per day

  LOYALTY_DEPLOY_WARNING_THRESHOLD: 30,
  LOYALTY_REFUSE_DEPLOY_THRESHOLD: 10, // at this point, hard block

  FATIGUE_ACCURACY_PENALTY_THRESHOLD: 75,
  FATIGUE_ACCURACY_PENALTY: -10, // applied to accuracy rolls
} as const
