/** Canonical IDs for authored events in data/definitions/events.json. */
export const EVENT_IDS = {
  ABSTRACT_CUSTODY_ALERT: 'event-abstract-custody-alert',
  BOUND_NPC_NOTICES_DIFFERENCE: 'event-bound-npc-notices-difference',
  BREN_ANCHOR_FOUND: 'event-bren-anchor-found',
  BREN_LEAVING_WARNING: 'event-bren-leaving-warning',
  BREN_LEFT: 'event-bren-left',
  CAPTIVITY_PREGNANCY_DISCOVERY: 'event-captivity-pregnancy-discovery',
  CITY_CRISIS: 'event-city-crisis',
  DEBT_FACTION_WARNING: 'event-debt-faction-warning',
  DOYLE_MILESTONE_HOLST: 'event-doyle-milestone-holst',
  GILDED_NOTICE: 'event-gilded-notice',
  HEIR_ANNOUNCEMENT: 'event-heir-announcement',
  HOLLOWS_ENTRY: 'event-hollows-entry',
  IDA_MILESTONE_CONTACT: 'event-ida-milestone-contact',
  MARION_MILESTONE_MOTIVATION: 'event-marion-milestone-motivation',
  MIRA_LOCATION: 'event-mira-location',
  MIRA_PRESSURE: 'event-mira-pressure',
  NPC_AMBITION_COMPARISON: 'event-npc-ambition-comparison',
  NPC_BETRAYAL: 'event-npc-betrayal',
  NPC_DOMINANCE_TENSION: 'event-npc-dominance-tension',
  NPC_FREED: 'event-npc-freed',
  NPC_IDEOLOGICAL_FRICTION: 'event-npc-ideological-friction',
  NPC_METHODS_DISAGREEMENT: 'event-npc-methods-disagreement',
  NPC_PAIRING_NOTICED: 'event-npc-pairing-noticed',
  NPC_PAIRING_PREGNANCY_DISCOVERY: 'event-npc-pairing-pregnancy-discovery',
  NPC_RECOGNITION_RIVALRY: 'event-npc-recognition-rivalry',
  PALE_APPROACH: 'event-pale-approach',
  RIVAL_ASHEN_COMPACT_BRIBE_WARNING: 'event-rival-ashen-compact-bribe-warning',
  RIVAL_ASHEN_COMPACT_COUNTER_LEAD: 'event-rival-ashen-compact-counter-lead',
  RIVAL_GILDED_HAND_BRIBE_WARNING: 'event-rival-gilded-hand-bribe-warning',
  RIVAL_GILDED_HAND_COUNTER_LEAD: 'event-rival-gilded-hand-counter-lead',
  RIVAL_IRON_COVENANT_BRIBE_WARNING: 'event-rival-iron-covenant-bribe-warning',
  RIVAL_IRON_COVENANT_COUNTER_LEAD: 'event-rival-iron-covenant-counter-lead',
  RIVAL_PALE_SISTERS_BRIBE_WARNING: 'event-rival-pale-sisters-bribe-warning',
  RIVAL_PALE_SISTERS_COUNTER_LEAD: 'event-rival-pale-sisters-counter-lead',
  SITE_PRESSURE_WARNING: 'event-site-pressure-warning',
  TITLE_NPC_BOND_OBJECTION: 'event-title-npc-bond-objection',
  TUTORIAL_END_DAY_RHYTHM: 'event-tutorial-end-day-rhythm',
  UNPAID_WAGES_UNREST: 'event-unpaid-wages-unrest',
  VAEL_MILESTONE_NETWORK: 'event-vael-milestone-network',
} as const

export type EventId = typeof EVENT_IDS[keyof typeof EVENT_IDS]
