import type { NpcRuntimeState } from './contracts'

/**
 * Creates a minimal valid NpcRuntimeState for testing.
 * All optional fields default to null/empty unless specified.
 */
export function createNpcRuntimeState(
  npcId: string,
  name: string,
  overrides?: Partial<NpcRuntimeState>,
): NpcRuntimeState {
  return {
    npcId,
    name,
    npcType: 'roster' as const,
    playerRosterMember: true,
    status: 'citizen' as const,
    assignment: 'idle' as const,
    assignedDistrictId: null,
    worldDisposition: null,
    lastContactDay: null,
    locationOverride: null,
    roomAssignment: null,
    dutyPostRoomId: null,
    activeTitle: null,
    wagesOwedDays: 0,
    trainingFocus: null,
    attributes: {
      might: 50,
      agility: 50,
      endurance: 50,
      intellect: 50,
      perception: 50,
      presence: 50,
      resolve: 50,
    },
    skills: {
      melee: 50,
      ranged: 50,
      medicine: 50,
      administration: 50,
      engineering: 50,
      negotiation: 50,
      survival: 50,
      security: 50,
      crafting: 50,
      performance: 50,
      academics: 50,
      intrigue: 50,
    },
    traits: {
      discipline: 50,
      ambition: 50,
      empathy: 50,
      ruthlessness: 50,
      prudence: 50,
      curiosity: 50,
      dominance: 50,
      loyalty: 50,
      vanity: 50,
      zeal: 50,
    },
    states: {
      health: 100,
      fatigue: 0,
      stress: 0,
      morale: 100,
      fear: 0,
      anger: 0,
      hunger: 0,
     
      intoxication: 0,
      hygiene: 0,
    },
    loadout: {
      primaryWeaponId: null,
      secondaryWeaponId: null,
      armorId: null,
      accessoryIds: [],
      consumableIds: [],
    },
    equipment: {
      weapon: null,
      armor: null,
      accessory: [],
    },
    personalFunds: {
      savings: 0,
      carriedCash: 0,
      lastWagePaymentDay: null,
      lastTipAmount: 0,
    },
    clothing: {
      head: null,
      torso: null,
      arms: null,
      legs: null,
      feet: null,
      full: null,
      undergarments: null,
      accessories: [],
    },
    armor: {
      lightTorso: null,
      lightLegs: null,
      heavyTorso: null,
      heavyLegs: null,
      shield: null,
    },
    npcMemory: [],
    factionRelationships: [],
    wardPersonalAllowance: {
      allowancePerWeek: 2,
      personalSavings: 0,
      lastAllowanceDay: null,
      allowedItems: [],
      restrictedItems: [],
    },
    arousalState: { level: 0, lastTriggerDay: null, triggerSource: null, cooldownUntilDay: null },
    bondStatus: null,
    npcArc: null,
    captivityState: undefined,
    pregnancyState: undefined,
    currentDirectiveId: null,
    directiveDeadlineDay: null,
    currentIntention: null,
    ...overrides,
  } as unknown as NpcRuntimeState
}
